name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: Configure
        run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release
          -j ${{ steps.cores.outputs.plus_one }}

      - name: Run
        working-directory: build
        run: ctest -C Release -j ${{ steps.cores.outputs.count }}
